---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: echoserver-v2-secure
  annotations:
    cert-manager.io/cluster-issuer: staging
spec:
  ingressClassName: external-nginx
  rules:
    - host: labs.molntek.com
      http:
        paths:
          - path: /
            pathType: Exact
            backend:
              service:
                name: echoserver-v2-secure
                port:
                  number: 8080
  tls:
    - hosts:
        - labs.molntek.com
      secretName: labs-molntek-com
